
# Dr. Nasib Singh Gill

+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                               |            |                                                                                                                                                                   |
+===============================================================================+============+===================================================================================================================================================================+
|                                                                               |            |                                                                                                                                                                   |
+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2.  Designation & Post Held                                                   | :          | > ***Head, Department of Computer Science & Applications,***                                                                                                      |
|                                                                               |            | >                                                                                                                                                                 |
|                                                                               |            | > ***Director, Centre for Distance and Online Education***                                                                                                        |
|                                                                               |            | >                                                                                                                                                                 |
|                                                                               |            | > ***Director, Digital Learning Centre,***                                                                                                                        |
|                                                                               |            | >                                                                                                                                                                 |
|                                                                               |            | > ***M.D. University, Rohtak-124001, Haryana, India.***                                                                                                           |
|                                                                               |            | >                                                                                                                                                                 |
|                                                                               |            | > **Phone:** +91 1262 293203                                                                                                                                      |
+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3.  Positions held earlier                                                    | :          | > ***-Head, Department of Computer Sc. & Applications***                                                                                                          |
|                                                                               |            | >                                                                                                                                                                 |
|                                                                               |            | > ***-Director, Directorate of Distance Education***                                                                                                              |
|                                                                               |            | >                                                                                                                                                                 |
|                                                                               |            | > ***-Director, University Computer Centre***                                                                                                                     |
|                                                                               |            | >                                                                                                                                                                 |
|                                                                               |            | > ***-Director, MDU Alumni***                                                                                                                                     |
|                                                                               |            | >                                                                                                                                                                 |
|                                                                               |            | > ***-Director, Public Relations***                                                                                                                               |
|                                                                               |            | >                                                                                                                                                                 |
|                                                                               |            | > ***-University Nodal Officer, AISHE, MHRD, Govt. of India***                                                                                                    |
+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                               |            |                                                                                                                                                                   |
+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5.  Academic Qualifications                                                   | :          | >   **Post Doctoral Research (Computer Sc.) from Brunel University, United Kingdom**                                                                              |
|                                                                               |            | >                                                                                                                                                                 |
|                                                                               |            | >   **Ph.D.(Computer Sc.)**                                                                                                                                       |
|                                                                               |            | >                                                                                                                                                                 |
|                                                                               |            | >   **MBA**                                                                                                                                                       |
+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 6.  Teaching Experience                                                       | :          | > 32+ years                                                                                                                                                       |
+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 7.  Research Experience                                                       | :          | > 29+ years                                                                                                                                                       |
+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 8.  Research Interests/Thrust Areas                                           | :          | > IoT, Machine Learning, Computer Vision, Cyber Security, Software Metrics, Component-based Metrics, Testing, Reusability, Data Mining and Data Warehousing, NLP, |
|                                                                               |            | >                                                                                                                                                                 |
|                                                                               |            | > Network Security, Information Security                                                                                                                          |
+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9.  Books & Research Papers                                                   | :          | **Books -- 4 (Independent), 1 (Joint), Courseware (6 Courses)**                                                                                                   |
|                                                                               |            |                                                                                                                                                                   |
|                                                                               |            | **Papers Published: 334**                                                                                                                                         |
|                                                                               |            |                                                                                                                                                                   |
|                                                                               |            | 1.  ***Published in International/National Journals: 198***                                                                                                       |
|                                                                               |            |                                                                                                                                                                   |
|                                                                               |            | 2.  ***Published as Chapters in Edited Books: 26***                                                                                                               |
|                                                                               |            |                                                                                                                                                                   |
|                                                                               |            | 3.  ***Published in Intnl. Conf. Proc., etc: 35***                                                                                                                |
|                                                                               |            |                                                                                                                                                                   |
|                                                                               |            | 4.  ***Published in National Conf. Proceedings, etc: 75***                                                                                                        |
+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10. Patents Filed/Published/Awarded                                           | :          | > 03 (Published)                                                                                                                                                  |
+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11. Contribution towards MHRD, Govt of India -- ARPIT through MOOCs on SWAYAM | :          | > Developed/Delivered 13 Course Modules on Pedagogical Innovations & Research Methodology                                                                         |
+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12. Ph.D. Thesis Guided /Guiding                                              | :          | > Awarded: 13, Guiding : 06                                                                                                                                       |
+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13. Conferences Attended/Sessions Conducted as Key Speaker/ Resource Person   | :          | > Conferences (International/National/Workshops): 130+                                                                                                            |
|                                                                               |            | >                                                                                                                                                                 |
|                                                                               |            | > Key Speaker/Resource Person in FDPs/RCs/OCs, etc: 140+                                                                                                          |
+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14. MCA/M.Sc. Projects & M.Tech. Thesis guided                                | :          | > MCA/M.Sc. Projects: about 375+;                                                                                                                                 |
|                                                                               |            | >                                                                                                                                                                 |
|                                                                               |            | > M.Tech Thesis: 18                                                                                                                                               |
+-------------------------------------------------------------------------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
